// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIUhmzkK85YltfbPSjD76eJNR-7EQo-Hk',
    appId: '1:127404149812:web:97c1840a64f76463858e61',
    messagingSenderId: '127404149812',
    projectId: 'capstone-bau-2025',
    authDomain: 'capstone-bau-2025.firebaseapp.com',
    databaseURL: 'https://capstone-bau-2025-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'capstone-bau-2025.firebasestorage.app',
    measurementId: 'G-2MTE91XPLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVt5ZgOnYjOqB_6NylYApnSyduuD_0vrE',
    appId: '1:127404149812:android:60c53da2b6e0a063858e61',
    messagingSenderId: '127404149812',
    projectId: 'capstone-bau-2025',
    databaseURL: 'https://capstone-bau-2025-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'capstone-bau-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRFhIpEdhPsYA-0zUvnTeR7fy1DBpnrw8',
    appId: '1:127404149812:ios:826d80aa58d168db858e61',
    messagingSenderId: '127404149812',
    projectId: 'capstone-bau-2025',
    databaseURL: 'https://capstone-bau-2025-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'capstone-bau-2025.firebasestorage.app',
    iosClientId: '127404149812-m37338somcfntael437dkutael36fv33.apps.googleusercontent.com',
    iosBundleId: 'com.example.smarthomeCapstone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRFhIpEdhPsYA-0zUvnTeR7fy1DBpnrw8',
    appId: '1:127404149812:ios:826d80aa58d168db858e61',
    messagingSenderId: '127404149812',
    projectId: 'capstone-bau-2025',
    databaseURL: 'https://capstone-bau-2025-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'capstone-bau-2025.firebasestorage.app',
    iosClientId: '127404149812-m37338somcfntael437dkutael36fv33.apps.googleusercontent.com',
    iosBundleId: 'com.example.smarthomeCapstone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIUhmzkK85YltfbPSjD76eJNR-7EQo-Hk',
    appId: '1:127404149812:web:5fbd01b8ffa47204858e61',
    messagingSenderId: '127404149812',
    projectId: 'capstone-bau-2025',
    authDomain: 'capstone-bau-2025.firebaseapp.com',
    databaseURL: 'https://capstone-bau-2025-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'capstone-bau-2025.firebasestorage.app',
    measurementId: 'G-67QNYWJ0ZF',
  );
}
